### ISSUE TITLE
Repo is probably named wrong now

### ISSUE THREAD

**Issue by ngelus** [Tomentos/JTT_GitBasics#3]
@Tomentos 
I saw that you just restructured the project to contain multiple tutorials in the future.
Despite this it is still called "JTT_**`GitBasics`**".
Are you sure that this is still the right name for the repo?

**Comment by Tomentos** [comment]
It is 11:45 o'clock on a Tuesday night. I am tired and ready for bed. When checking my phone though, I realized a mistake. I forgot to rename a GitHub repository.
In a swirl of emotions, I ask myself: „Should I turn my computer back on to change the name of this repository?”
The answer I came to was no.

**Comment by Tomentos** [comment]
Aight it's renamed now

**Comment by ngelus** [comment]
> It is 11:45 o'clock on a Tuesday night. I am tired and ready for bed. When checking my phone though, I realized a mistake. I forgot to rename a GitHub repository. In a swirl of emotions, I ask myself: „Should I turn my computer back on to change the name of this repository?” The answer I came to was no.

Such poetry. Very storybuiding. Much wow

**Comment by ngelus** [comment]
> Aight it's renamed now

Perfect
